import turtle

#небо
screen = turtle.Screen()
screen.bgcolor("lightblue") 

turtle.speed(0)

#пляж
turtle.penup()
turtle.goto(-300, 0)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor("yellow")
turtle.forward(600)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(600)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.end_fill()

#вода
turtle.penup()
turtle.goto(-300, 100)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor("blue")
turtle.forward(600)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(600)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.end_fill()

#ствол пальмы
turtle.penup()
turtle.goto(100, -50)  
turtle.pendown()
for i in range(5):
    turtle.penup()
    turtle.goto(100, -50 + i * 20)
    turtle.pendown()
    turtle.begin_fill()
    turtle.fillcolor("brown")
    turtle.circle(10)
    turtle.end_fill()


#кокосы(желтые)
turtle.penup()
turtle.goto(110, 25)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor("yellow")
turtle.circle(8)
turtle.end_fill()
turtle.penup()
turtle.goto(90, 25) 
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor("yellow")
turtle.circle(8)
turtle.end_fill()
turtle.penup()
turtle.goto(100, 15) 
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor("yellow")
turtle.circle(8)
turtle.end_fill()

#листья у пальмы
turtle.penup()
turtle.goto(100, 50)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor("green")
turtle.setheading(15)
turtle.forward(55)
turtle.right(90)
turtle.forward(15)
turtle.right(90)
turtle.forward(55)
turtle.right(90)
turtle.forward(15)
turtle.right(90)
turtle.end_fill()

turtle.penup()
turtle.goto(100, 50)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor("green")
turtle.setheading(-15) 
turtle.forward(55)
turtle.right(90)
turtle.forward(15)
turtle.right(90)
turtle.forward(55)
turtle.right(90)
turtle.forward(15)
turtle.right(90)
turtle.end_fill()

turtle.penup()
turtle.goto(100, 40)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor("green")
turtle.setheading(-165) 
turtle.forward(55)
turtle.right(90)
turtle.forward(15)
turtle.right(90)
turtle.forward(55)
turtle.right(90)
turtle.forward(15)
turtle.right(90)
turtle.end_fill()

turtle.penup()
turtle.goto(95, 35)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor("green")
turtle.setheading(-195)  
turtle.forward(55)
turtle.right(90)
turtle.forward(15)
turtle.right(90)
turtle.forward(55)
turtle.right(90)
turtle.forward(15)
turtle.right(90)
turtle.end_fill()



turtle.done()
